apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytewax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytewax
  template:
    metadata:
      labels:
        app: bytewax
    spec:
      containers:
      - name: bytewax
        image: oratio_bytewax_pipeline
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bytewax
spec:
  ports:
  - port: 8081
  selector:
    app: bytewax
