# version: '3'
# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "8080:8080"
#     networks:
#       - my-network

#   frontend:
#     build:
#       context: ./ui
#     ports:
#       - "8501:8501"
#     depends_on:
#       - backend
#     networks:
#       - my-network

# networks:
#   my-network:
#     driver: bridge



version: '3.8'

services:
  backend:
    image: oratio_prototype_backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    image: oratio_prototype_frontend
    build:
      context: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
