version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - ui

  ui:
    build: ./ui
    ports:
      - "8501:8501"
