apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdc
  template:
    metadata:
      labels:
        app: cdc
    spec:
      containers:
      - name: cdc
        image: oratio-cdc
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cdc
spec:
  ports:
  - port: 8080
  selector:
    app: cdc
