apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      role: replica3
  template:
    metadata:
      labels:
        app: mongo
        role: replica3
    spec:
      containers:
      - name: mongo
        image: mongo:5
        command: ["mongod", "--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
        ports:
        - containerPort: 30003
        volumeMounts:
        - name: mongo-replica-3-data
          mountPath: /data/db
      volumes:
      - name: mongo-replica-3-data
        persistentVolumeClaim:
          claimName: mongo-replica-3-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo3
spec:
  ports:
  - port: 30003
    targetPort: 30003
  selector:
    app: mongo
    role: replica3
