
FROM node:18-alpine as build

WORKDIR /app
COPY ../frontend/package*.json ./
RUN npm ci
COPY ../frontend/ .
RUN npm run build

# Install serve globally
RUN npm install -g serve

# Expose port 3000 (serve's default port)
EXPOSE 3000

# Start serve
CMD ["serve", "-s", "dist"]